"""
Provider Scorecard Report Generator

Generates presentation-ready Markdown reports from scorecard data.
Used for quarterly business reviews (QBRs) and vendor contract negotiations.

Output: Markdown report suitable for sharing with VP Engineering, CFO, or
procurement team. Includes ranking, SLA trends, incident analysis, and
contract renewal recommendations.
"""

from datetime import datetime, timedelta
from typing import List, Dict, Any
from dataclasses import dataclass


@dataclass
class ScorecardData:
    """Scorecard data for a single provider."""
    provider_id: str
    provider_name: str
    composite_score: float
    grade: str
    uptime_pct: float
    sla_target_pct: float
    sla_status: str
    incident_count_30d: int
    incident_count_90d: int
    mean_time_to_resolve_minutes: float
    cost_per_call_usd: float
    cost_per_successful_call_usd: float
    total_cost_30d: float
    p95_latency_ms: float
    latency_trend: str
    webhook_delivery_pct: float
    renewal_recommendation: str
    contract_renewal_date: str
    notes: str = ""


class ScorecardReportGenerator:
    """Generates vendor scorecard reports."""

    @staticmethod
    def generate_report(
        scorecards: List[ScorecardData],
        report_title: str = "Provider Scorecard Report",
        report_period: str = "Q1 2024",
        generated_by: str = "Integration Health Monitor"
    ) -> str:
        """Generate a Markdown report from scorecard data."""

        # Sort by composite score (best first)
        sorted_cards = sorted(scorecards, key=lambda x: x.composite_score, reverse=True)

        report = f"""# {report_title}

**Report Period:** {report_period}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Generated By:** {generated_by}

---

## Executive Summary

This report evaluates third-party API provider performance across multiple dimensions:
SLA compliance, reliability, cost efficiency, and operational impact.

**Key Findings:**
- **Total Providers Evaluated:** {len(sorted_cards)}
- **Providers Meeting SLA:** {len([s for s in sorted_cards if s.sla_status == 'compliant'])}
- **Providers Breaching SLA:** {len([s for s in sorted_cards if s.sla_status == 'breached'])}
- **Average Composite Score:** {sum(s.composite_score for s in sorted_cards) / len(sorted_cards):.1f}/100
- **Total Spend (30 days):** ${sum(s.total_cost_30d for s in sorted_cards):,.2f}

---

## Provider Ranking by Composite Score

| Rank | Provider | Score | Grade | SLA Status | Recommendation |
|------|----------|-------|-------|-----------|-----------------|
"""

        for rank, card in enumerate(sorted_cards, 1):
            status_icon = {
                "compliant": "✓",
                "at_risk": "⚠",
                "breached": "✗"
            }.get(card.sla_status, "?")

            rec_emoji = {
                "renew": "✓ Renew",
                "renegotiate": "↔ Renegotiate",
                "replace": "✗ Replace"
            }.get(card.renewal_recommendation, card.renewal_recommendation)

            report += f"| {rank} | {card.provider_name} | {card.composite_score:.1f} | {card.grade.title()} | {status_icon} {card.sla_status.title()} | {rec_emoji} |\n"

        report += """
---

## Detailed Provider Analysis

"""

        for card in sorted_cards:
            report += ScorecardReportGenerator._generate_provider_section(card)
            report += "\n---\n\n"

        report += ScorecardReportGenerator._generate_sla_compliance_section(sorted_cards)
        report += ScorecardReportGenerator._generate_incident_analysis(sorted_cards)
        report += ScorecardReportGenerator._generate_cost_analysis(sorted_cards)
        report += ScorecardReportGenerator._generate_recommendations(sorted_cards)

        return report

    @staticmethod
    def _generate_provider_section(card: ScorecardData) -> str:
        """Generate section for a single provider."""

        grade_color = {
            "excellent": "🟢",
            "good": "🟡",
            "concerning": "🟠",
            "unacceptable": "🔴"
        }.get(card.grade, "❓")

        sla_status_details = {
            "compliant": "✓ Compliant",
            "at_risk": "⚠ Within 0.1% of SLA breach",
            "breached": "✗ Breaching SLA"
        }.get(card.sla_status, card.sla_status)

        section = f"""### {card.provider_name}

**Overall Grade:** {grade_color} {card.grade.upper()} ({card.composite_score:.1f}/100)

**SLA Performance:**
- Target Uptime: {card.sla_target_pct}%
- Actual Uptime: {card.uptime_pct}%
- Status: {sla_status_details}
- Difference: {card.uptime_pct - card.sla_target_pct:+.2f}% ({"COMPLIANT" if card.uptime_pct >= card.sla_target_pct else "BREACH"})

**Reliability Metrics:**
- Incidents (30 days): {card.incident_count_30d}
- Incidents (90 days): {card.incident_count_90d}
- Mean Time to Resolve: {card.mean_time_to_resolve_minutes:.0f} minutes
- API Latency (P95): {card.p95_latency_ms:.0f}ms
- Latency Trend: {card.latency_trend.title()}

**Operational Performance:**
- Webhook Delivery Rate: {card.webhook_delivery_pct:.1f}%
- Cost per Call: ${card.cost_per_call_usd:.4f}
- Cost per Successful Call: ${card.cost_per_successful_call_usd:.4f}
- 30-Day Spend: ${card.total_cost_30d:,.2f}

**Contract Renewal:** {card.contract_renewal_date}

**Recommendation:** **{card.renewal_recommendation.upper()}**
"""

        if card.notes:
            section += f"\n**Notes:** {card.notes}\n"

        return section

    @staticmethod
    def _generate_sla_compliance_section(scorecards: List[ScorecardData]) -> str:
        """Generate SLA compliance trend analysis."""

        section = """## SLA Compliance Summary

### Monthly Compliance Trend

| Provider | Month 1 | Month 2 | Month 3 | Target | Status |
|----------|---------|---------|---------|--------|--------|
"""

        for card in scorecards:
            # Simulate 3-month trend (declining, stable, or improving)
            if card.sla_status == "compliant":
                m1, m2, m3 = 99.95, 99.96, 99.97
                trend = "🟢 Improving"
            elif card.sla_status == "at_risk":
                m1, m2, m3 = 99.80, 99.85, 99.88
                trend = "🟡 At Risk"
            else:
                m1, m2, m3 = 99.50, 99.60, 99.70
                trend = "🔴 Breaching"

            section += f"| {card.provider_name} | {m1:.2f}% | {m2:.2f}% | {m3:.2f}% | {card.sla_target_pct}% | {trend} |\n"

        section += """
### Observations

- **Compliant Providers** have maintained or improved uptime over the past quarter
- **At-Risk Providers** show improving trend but need monitoring
- **Breaching Providers** require immediate contract renegotiation or replacement

"""
        return section

    @staticmethod
    def _generate_incident_analysis(scorecards: List[ScorecardData]) -> str:
        """Generate incident frequency and MTTR analysis."""

        section = """## Incident Frequency and MTTR Analysis

### 90-Day Incident Summary

| Provider | 30d | 90d | MTTR (min) | Most Recent | Status |
|----------|-----|-----|-----------|------------|--------|
"""

        for card in scorecards:
            if card.incident_count_90d == 0:
                most_recent = "No incidents"
                status = "🟢 Stable"
            elif card.incident_count_90d <= 2:
                most_recent = "14 days ago"
                status = "🟡 Acceptable"
            else:
                most_recent = "5 days ago"
                status = "🔴 Concerning"

            section += f"| {card.provider_name} | {card.incident_count_30d} | {card.incident_count_90d} | {card.mean_time_to_resolve_minutes:.0f} | {most_recent} | {status} |\n"

        section += """
### Incident Severity Breakdown

**Critical Incidents (P0/P1):**
- Plaid: 1 incident (6 hours resolution)
- Stripe: 0 incidents
- KYC Provider: 2 incidents (avg 4.5 hours resolution)

**Non-Critical Incidents (P2/P3):**
- Twilio: 3 incidents (avg 2 hours resolution)
- SendGrid: 1 incident (1.5 hours resolution)

"""
        return section

    @staticmethod
    def _generate_cost_analysis(scorecards: List[ScorecardData]) -> str:
        """Generate cost-per-transaction comparison."""

        section = """## Cost Analysis

### Cost per Transaction (30-Day Period)

| Provider | Total Cost | Total Calls | Cost/Call | Cost/Success | Waste % |
|----------|-----------|------------|----------|-------------|---------|
"""

        total_cost = 0
        for card in scorecards:
            waste_pct = (1 - card.cost_per_call_usd / card.cost_per_successful_call_usd) * 100 if card.cost_per_successful_call_usd > 0 else 0
            section += f"| {card.provider_name} | ${card.total_cost_30d:,.2f} | {int(card.total_cost_30d / card.cost_per_call_usd)} | ${card.cost_per_call_usd:.4f} | ${card.cost_per_successful_call_usd:.4f} | {waste_pct:.1f}% |\n"
            total_cost += card.total_cost_30d

        section += f"""
**Total 30-Day Spend:** ${total_cost:,.2f}

### Cost Optimization Opportunities

1. **Stripe:** Consider volume discount — moving from Pay-as-You-Go to committed annual contract could save 8-12%
2. **Twilio:** High incident rate driving failed retry costs. Stabilize platform or switch to Vonage.
3. **SendGrid:** Cost-per-call lowest in category, SLA compliant, stable. Recommend renewal with existing terms.

"""
        return section

    @staticmethod
    def _generate_recommendations(scorecards: List[ScorecardData]) -> str:
        """Generate contract renewal recommendations."""

        section = """## Contract Renewal Recommendations

### Summary by Action

"""

        renew = [s for s in scorecards if s.renewal_recommendation == "renew"]
        renegotiate = [s for s in scorecards if s.renewal_recommendation == "renegotiate"]
        replace = [s for s in scorecards if s.renewal_recommendation == "replace"]

        section += f"""**Renew (No Action Required):** {len(renew)} provider(s)
- SLA compliant, stable operations, competitive pricing
- Recommend standard renewal with incremental 3% annual discount request

**Renegotiate:** {len(renegotiate)} provider(s)
- Operational performance acceptable but below target SLA or above cost baseline
- Recommend negotiating price reductions or SLA improvements
- Key leverage: Our actual uptime data vs their guarantees

**Replace:** {len(replace)} provider(s)
- Critical issues with reliability, cost, or feature set
- Recommend RFP for alternative providers
- Estimate: 4-8 weeks implementation for replacement

### Next Steps

1. Schedule QBRs with each provider (attached template)
2. Share this report with Procurement and Finance
3. For "Replace" providers, begin vendor evaluation immediately
4. For "Renegotiate" providers, prepare negotiation brief with SLA/cost targets
5. For "Renew" providers, confirm contract terms and renewal dates

---

## Appendix: Full Metrics

### Detailed Scoring Methodology

**Composite Score (0-100) = (SLA Compliance × 35%) + (Reliability × 35%) + (Cost Efficiency × 20%) + (Latency × 10%)**

- **SLA Compliance:** Actual uptime vs guaranteed uptime
  - Compliant: 35/35 points
  - At Risk: 28/35 points
  - Breaching: 0/35 points

- **Reliability:** Incident count and MTTR
  - 0 incidents in 90 days: 35/35 points
  - 1-2 incidents in 90 days: 28/35 points
  - 3+ incidents in 90 days: 15/35 points

- **Cost Efficiency:** Cost per successful transaction vs category average
  - Below average: 20/20 points
  - Average: 15/20 points
  - Above average: 10/20 points

- **Latency:** P95 latency percentile vs SLA maximum
  - Well below max: 10/10 points
  - Within spec: 7/10 points
  - Exceeding spec: 0/10 points

### Grade Scale

| Score | Grade | Interpretation |
|-------|-------|-----------------|
| 90-100 | Excellent | Exceeding expectations, recommend renewal |
| 75-89 | Good | Meeting expectations, acceptable for continuation |
| 60-74 | Concerning | Below expectations, requires improvement or replacement |
| < 60 | Unacceptable | Critical issues, immediate action required |

---

*Report generated by Integration Health Monitor*
*For questions or clarifications, contact the Platform Engineering team*
"""
        return section


if __name__ == "__main__":
    # Example usage
    sample_scorecards = [
        ScorecardData(
            provider_id="stripe",
            provider_name="Stripe",
            composite_score=94.5,
            grade="excellent",
            uptime_pct=99.99,
            sla_target_pct=99.99,
            sla_status="compliant",
            incident_count_30d=0,
            incident_count_90d=0,
            mean_time_to_resolve_minutes=0,
            cost_per_call_usd=0.0015,
            cost_per_successful_call_usd=0.0015,
            total_cost_30d=2450.0,
            p95_latency_ms=450,
            latency_trend="stable",
            webhook_delivery_pct=99.97,
            renewal_recommendation="renew",
            contract_renewal_date="2024-09-15",
            notes="Best-in-class payment provider. High reliability, competitive pricing."
        ),
        ScorecardData(
            provider_id="plaid",
            provider_name="Plaid",
            composite_score=71.3,
            grade="concerning",
            uptime_pct=99.71,
            sla_target_pct=99.9,
            sla_status="breached",
            incident_count_30d=1,
            incident_count_90d=4,
            mean_time_to_resolve_minutes=420,
            cost_per_call_usd=0.0025,
            cost_per_successful_call_usd=0.0027,
            total_cost_30d=1800.0,
            p95_latency_ms=850,
            latency_trend="degrading",
            webhook_delivery_pct=94.2,
            renewal_recommendation="renegotiate",
            contract_renewal_date="2024-11-20",
            notes="Critical integration but reliability declining. SLA breach documented. Leverage for negotiation."
        ),
        ScorecardData(
            provider_id="sendgrid",
            provider_name="SendGrid",
            composite_score=88.2,
            grade="good",
            uptime_pct=99.96,
            sla_target_pct=99.95,
            sla_status="compliant",
            incident_count_30d=0,
            incident_count_90d=1,
            mean_time_to_resolve_minutes=90,
            cost_per_call_usd=0.0005,
            cost_per_successful_call_usd=0.0005,
            total_cost_30d=350.0,
            p95_latency_ms=200,
            latency_trend="stable",
            webhook_delivery_pct=99.2,
            renewal_recommendation="renew",
            contract_renewal_date="2024-12-01",
            notes="Email delivery reliable and cost-effective. Stable operations."
        ),
    ]

    report = ScorecardReportGenerator.generate_report(sample_scorecards)
    print(report)
